# Generated by Django 4.0.4 on 2022-05-10 20:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=75)),
                ('default', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flex.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flex.user')),
            ],
        ),
        migrations.CreateModel(
            name='FlexAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flex', models.FloatField()),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flex.assessment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flex.user')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flex.assessment')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flex.course')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usercourse',
            constraint=models.UniqueConstraint(fields=('user_id', 'course_id'), name='User and Course unique'),
        ),
        migrations.AddConstraint(
            model_name='assessmentcourse',
            constraint=models.UniqueConstraint(fields=('assessment_id', 'course_id'), name='Assessment and Course unique'),
        ),
    ]
