# Generated by Django 4.0.4 on 2022-05-12 18:50

from django.db import migrations

from flex.utils import create_groups


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
