# Generated by Django 4.0.4 on 2022-05-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentgroup',
            name='allocation',
        ),
    ]
