# Generated by Django 4.0.4 on 2022-05-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexassessment',
            name='flex',
            field=models.DecimalField(
                decimal_places=2, max_digits=5, null=True),
        ),
    ]
