# Generated by Django 4.0.4 on 2022-05-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='login_id',
            field=models.CharField(max_length=100),
        ),
    ]
