# Generated by Django 4.0.4 on 2022-05-31 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_remove_assignmentgroup_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='id',
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                primary_key=True,
                serialize=False),
        ),
    ]
