# Generated by Django 4.0.4 on 2022-07-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={},
        ),
    ]
