# Generated by Django 4.0.4 on 2023-05-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_assessment', '0002_alter_assessment_default_alter_assessment_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='comment_instructions',
            field=models.TextField(blank=True, default='Please enter your reasons for the choices you made.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='welcome_instructions',
            field=models.TextField(blank=True, default='Welcome to Flexible Assessment, the system that allows students to decide how their final grades will be weighted. Please enter your desired weights in the fields below, agree to the terms, and click Submit.', null=True),
        ),
    ]
