# Generated by Django 4.0.4 on 2023-05-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_assessment', '0002_alter_assessment_default_alter_assessment_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='comment_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='welcome_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
