# Generated by Django 4.0.4 on 2022-07-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_assessment', '0002_alter_assessment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexassessment',
            options={},
        ),
    ]
