# Generated by Django 4.0.4 on 2022-07-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_assessment', '0003_alter_flexassessment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flexible_assessment.assignmentgroup'),
        ),
    ]
