# Generated by Django 4.2.5 on 2023-09-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flexible_assessment", "0003_course_comment_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="order",
            field=models.IntegerField(default=100000),
        ),
    ]
