# Generated by Django 4.0.4 on 2022-07-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_assessment', '0004_alter_assessment_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='group',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='AssignmentGroup',
        ),
    ]
