# Generated by Django 4.2.5 on 2023-11-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flexible_assessment", "0004_assessment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="calendar_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
