# Generated by Django 4.0.4 on 2024-02-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_assessment', '0005_course_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexassessment',
            name='overidden',
            field=models.BooleanField(default=False),
        ),
    ]
