# Generated by Django 4.0.4 on 2024-02-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_assessment', '0006_flexassessment_overidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flexassessment',
            old_name='overidden',
            new_name='override',
        ),
    ]
