# Generated by Django 4.2.15 on 2025-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flexible_assessment", "0007_rename_overidden_flexassessment_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="flex_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
