# Generated by Django 6.0.8 on 2026-09-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flexible_assessment", "0008_course_flex_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="usercourse",
            constraint=models.CheckConstraint(
                condition=models.Q(("locked", False), ("role", 4), _connector="OR"),
                name="Only students can be locked",
            ),
        ),
    ]
